import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { Header } from "@/components/universal/header";
import { Toaster } from "@/components/ui/sonner";
import {
  AlertTriangleIcon,
  Ban,
  CheckCircle2,
  Info,
  Loader,
} from "lucide-react";

const inter = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Toaster
            position="bottom-right"
            icons={{
              success: <CheckCircle2 className="size-4" />,
              info: <Info className="size-4" />,
              warning: <AlertTriangleIcon className="size-4" />,
              error: <Ban className="size-4" />,
              loading: <Loader className="size-4" />,
            }}
            toastOptions={{
              unstyled: false,
              classNames: {
                error: "border-destructive text-destructive",
                success: "border-green-400",
                warning: "border-yellow-400",
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
